---
title: Ferienwohnung Kaintz
timezone: Europe/Vienna
defaults:
- scope:
    path: assets/img
  values:
    image: true
email: stefan@skoegl.net
description: Ferienwohnung in Podersdorf
baseurl: "/"
url: https://www.ferienwohnung-kaintz.at
lang: de
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
