---
title: Ferienwohnung Kaintz
timezone: Europe/Vienna
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/img
  values:
    image: true
email: stefan@skoegl.net
description: Ferienwohnung in Podersdorf
baseurl: "/"
url: https://www.ferienwohnung-kaintz.at
lang: de
google_analytics: UA-107321-12
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
